version: 0.1
phases:
  pre_build:
    commands:
      - apt update
      - node -v
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync "public/" "s3://ocius-static-website" --delete
      - aws cloudfront create-invalidation --distribution-id E3DSYTEJZITXF6 --paths "/*"
artifacts:
  base-directory: public
  files:
    - '../{1}'
  discard-paths: yes