version: 0.1
phases:
  install:
    commands:
      - "npm install"
      - "npm install -g gatsby"
      - "npm install -g lighthouse-ci"
      - "apt update"
      - "apt install -y chromium-browser"
      - "gatsby build"
  pre_build:
    commands:
      - 'echo "Run gatsby locally"'
      - 'gatsby serve &'
      - 'echo "Ensure changes meet lighthouse thresholds"'
      - "lighthouse-ci http://localhost:9000/ --performance=99 --best-practices=99 --accessibility=99 --seo=99"
  build:
    commands:
      - 'echo "Upload build output to S3"'
      - 'aws s3 sync "public/" "s3://ocius-static-website" --delete --acl "public-read"'
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
