version: 0.1
phases:    
    install:        
        commands:            
            - 'npm install'
            - 'npm install -g gatsby'    
    build:        
        commands:            
            - 'gatsby build'
artifacts:    
    base-directory: public    
    files:        
        - '**/*'    
    discard-paths: yes