version: 0.1
phases:
  install:
    commands:
      - "npm install"
      - "npm install -g gatsby"
  build:
    commands:
      - "gatsby build"
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://ocius-static-website" --delete --acl "public-read"'
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: yes
