version: 0.1
phases:    
    install:        
        commands:            
            - 'npm install -g gatsby'    
    pre_build:        
        commands:            
            - 'npm install'    
    build:        
        commands:            
            - 'gatsby build'    
artifacts:    
    base-directory: public
    files:        
        - '**/*'    
    discard-paths: yes